# debug: true
spring:
  application:
    name: RecommendationService
  main:
    allow-bean-definition-overriding: true
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/cryptodb
    username: ${DB_USERNAME:xm}
    password: ${DB_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

crypto:
  loader:
    folder: ${CRYPTO_PRICES_FOLDER_PATH:./src/main/resources/prices}