spring.application.name=RecommendationService
# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/cryptodb
spring.datasource.username=xm
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

# Explicitly set the dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA config
spring.jpa.hibernate.ddl-auto=update